// Mock data for demo mode — allows the app to work without Firebase
import { generateId } from './formatters';

const now = new Date();
const hoursAgo = (h) => new Date(now - h * 3600000);
const daysAgo = (d) => new Date(now - d * 86400000);

export const MOCK_USER = {
  uid: 'demo-user-001',
  email: 'demo@crisisconnect.app',
  displayName: 'Alex Rivera',
  role: 'admin',
  phone: '+1-555-0123',
  location: 'Mumbai, India',
  createdAt: daysAgo(30),
};

export const MOCK_REQUESTS = [
  {
    id: generateId(),
    title: 'Family trapped on rooftop — urgent rescue needed',
    description: 'A family of 5 including 2 children and an elderly person is trapped on the rooftop of a 2-story building. Water level is rising fast. They need immediate boat rescue.',
    category: 'rescue',
    priority: 'critical',
    status: 'pending',
    location: 'Sector 12, Andheri East, Mumbai',
    contactName: 'Rahul Sharma',
    contactPhone: '+91-98765-43210',
    peopleAffected: 5,
    createdAt: hoursAgo(0.5),
    updatedAt: hoursAgo(0.5),
    assignedTo: null,
    createdBy: 'user-001',
  },
  {
    id: generateId(),
    title: 'Medical emergency — diabetic patient needs insulin',
    description: 'An elderly diabetic patient has run out of insulin supply. They need insulin injections urgently. Patient is stable but deteriorating. Located on the 3rd floor of building.',
    category: 'medical',
    priority: 'critical',
    status: 'assigned',
    location: 'Block C, Kalyan Township',
    contactName: 'Priya Patel',
    contactPhone: '+91-87654-32109',
    peopleAffected: 1,
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(1),
    assignedTo: 'vol-002',
    createdBy: 'user-002',
  },
  {
    id: generateId(),
    title: 'Food and water needed for 30 people at community center',
    description: 'About 30 people including 8 children have taken shelter at the community center. They have been without food for 18 hours. Clean drinking water is also urgently needed.',
    category: 'food',
    priority: 'high',
    status: 'in_progress',
    location: 'Community Center, Dadar West',
    contactName: 'Mohammed Khan',
    contactPhone: '+91-76543-21098',
    peopleAffected: 30,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(2),
    assignedTo: 'vol-001',
    createdBy: 'user-003',
  },
  {
    id: generateId(),
    title: 'Temporary shelter needed for displaced families',
    description: '12 families from the low-lying area have been displaced. They need temporary shelter, blankets, and basic supplies. Currently taking refuge in a school building.',
    category: 'shelter',
    priority: 'high',
    status: 'pending',
    location: 'Government School, Kurla East',
    contactName: 'Sunita Devi',
    contactPhone: '+91-65432-10987',
    peopleAffected: 48,
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
    assignedTo: null,
    createdBy: 'user-004',
  },
  {
    id: generateId(),
    title: 'Transport needed to evacuate elderly residents',
    description: 'A group of 15 elderly residents at an old age home need to be evacuated to higher ground. Some have mobility issues and need wheelchair-accessible transport.',
    category: 'transport',
    priority: 'high',
    status: 'assigned',
    location: 'Sunshine Old Age Home, Thane',
    contactName: 'Dr. Anil Mehta',
    contactPhone: '+91-54321-09876',
    peopleAffected: 15,
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(1.5),
    assignedTo: 'vol-003',
    createdBy: 'user-005',
  },
  {
    id: generateId(),
    title: 'Clean drinking water supply for relief camp',
    description: 'Relief camp at the stadium has 200+ people but water supply has been contaminated. Need clean drinking water and water purification tablets urgently.',
    category: 'food',
    priority: 'critical',
    status: 'in_progress',
    location: 'Municipal Stadium, Borivali',
    contactName: 'Ravi Kumar',
    contactPhone: '+91-43210-98765',
    peopleAffected: 200,
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(1),
    assignedTo: 'vol-004',
    createdBy: 'user-006',
  },
  {
    id: generateId(),
    title: 'Clothing and blankets for children at shelter',
    description: 'Around 25 children at the shelter are without proper clothing. Nights are cold and they need warm clothes and blankets urgently.',
    category: 'clothing',
    priority: 'medium',
    status: 'pending',
    location: 'Relief Shelter #3, Powai',
    contactName: 'Anjali Singh',
    contactPhone: '+91-32109-87654',
    peopleAffected: 25,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
    assignedTo: null,
    createdBy: 'user-007',
  },
  {
    id: generateId(),
    title: 'Road clearance needed — fallen tree blocking access',
    description: 'A large tree has fallen blocking the main road to the relief camp. Emergency vehicles cannot pass through. Need volunteers with cutting equipment.',
    category: 'other',
    priority: 'medium',
    status: 'resolved',
    location: 'Main Road, Near Vikhroli Station',
    contactName: 'Suresh Patil',
    contactPhone: '+91-21098-76543',
    peopleAffected: 0,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(12),
    assignedTo: 'vol-005',
    createdBy: 'user-008',
  },
  {
    id: generateId(),
    title: 'First aid supplies needed at community hall',
    description: 'Makeshift medical camp at the community hall is running low on first aid supplies — bandages, antiseptics, painkillers, and ORS packets.',
    category: 'medical',
    priority: 'high',
    status: 'in_progress',
    location: 'Community Hall, Chembur',
    contactName: 'Dr. Kavita Rao',
    contactPhone: '+91-10987-65432',
    peopleAffected: 50,
    createdAt: hoursAgo(7),
    updatedAt: hoursAgo(3),
    assignedTo: 'vol-002',
    createdBy: 'user-009',
  },
  {
    id: generateId(),
    title: 'Rescue needed for pets left behind in evacuation',
    description: 'Multiple pets including dogs and cats were left behind during emergency evacuation in the housing society. Need animal rescue volunteers.',
    category: 'rescue',
    priority: 'low',
    status: 'pending',
    location: 'Green Valley Housing, Mulund',
    contactName: 'Neha Gupta',
    contactPhone: '+91-09876-54321',
    peopleAffected: 0,
    createdAt: hoursAgo(10),
    updatedAt: hoursAgo(10),
    assignedTo: null,
    createdBy: 'user-010',
  },
];

export const MOCK_VOLUNTEERS = [
  {
    id: 'vol-001',
    name: 'Arjun Nair',
    email: 'arjun@example.com',
    phone: '+91-98765-11111',
    skills: ['First Aid', 'Driving', 'Logistics'],
    location: 'Mumbai Central',
    available: true,
    assignedRequests: 3,
    completedRequests: 12,
    rating: 4.8,
    joinedAt: daysAgo(60),
  },
  {
    id: 'vol-002',
    name: 'Dr. Meera Iyer',
    email: 'meera@example.com',
    phone: '+91-98765-22222',
    skills: ['Medical', 'First Aid', 'Counseling'],
    location: 'Dadar',
    available: true,
    assignedRequests: 2,
    completedRequests: 28,
    rating: 4.9,
    joinedAt: daysAgo(120),
  },
  {
    id: 'vol-003',
    name: 'Vikram Joshi',
    email: 'vikram@example.com',
    phone: '+91-98765-33333',
    skills: ['Driving', 'Search & Rescue', 'Construction'],
    location: 'Thane',
    available: true,
    assignedRequests: 1,
    completedRequests: 8,
    rating: 4.6,
    joinedAt: daysAgo(45),
  },
  {
    id: 'vol-004',
    name: 'Fatima Sheikh',
    email: 'fatima@example.com',
    phone: '+91-98765-44444',
    skills: ['Cooking', 'Logistics', 'Communication'],
    location: 'Borivali',
    available: true,
    assignedRequests: 1,
    completedRequests: 15,
    rating: 4.7,
    joinedAt: daysAgo(90),
  },
  {
    id: 'vol-005',
    name: 'Rajesh Verma',
    email: 'rajesh@example.com',
    phone: '+91-98765-55555',
    skills: ['Construction', 'Search & Rescue', 'Driving'],
    location: 'Vikhroli',
    available: false,
    assignedRequests: 0,
    completedRequests: 22,
    rating: 4.5,
    joinedAt: daysAgo(180),
  },
  {
    id: 'vol-006',
    name: 'Ananya Das',
    email: 'ananya@example.com',
    phone: '+91-98765-66666',
    skills: ['Child Care', 'Counseling', 'Communication'],
    location: 'Powai',
    available: true,
    assignedRequests: 0,
    completedRequests: 6,
    rating: 4.9,
    joinedAt: daysAgo(30),
  },
  {
    id: 'vol-007',
    name: 'Sameer Patel',
    email: 'sameer@example.com',
    phone: '+91-98765-77777',
    skills: ['IT Support', 'Logistics', 'Communication'],
    location: 'Andheri',
    available: true,
    assignedRequests: 0,
    completedRequests: 4,
    rating: 4.3,
    joinedAt: daysAgo(15),
  },
];

export const MOCK_RESOURCES = [
  { id: generateId(), type: 'food', name: 'Food Packets', quantity: 450, capacity: 1000, unit: 'packets', lastUpdated: hoursAgo(1) },
  { id: generateId(), type: 'water', name: 'Water Bottles', quantity: 1200, capacity: 2000, unit: 'liters', lastUpdated: hoursAgo(2) },
  { id: generateId(), type: 'medicine', name: 'Medicine Kits', quantity: 85, capacity: 200, unit: 'kits', lastUpdated: hoursAgo(3) },
  { id: generateId(), type: 'blankets', name: 'Blankets', quantity: 320, capacity: 500, unit: 'pieces', lastUpdated: hoursAgo(1.5) },
  { id: generateId(), type: 'tents', name: 'Tents', quantity: 45, capacity: 100, unit: 'units', lastUpdated: hoursAgo(5) },
  { id: generateId(), type: 'clothing', name: 'Clothing Sets', quantity: 180, capacity: 400, unit: 'sets', lastUpdated: hoursAgo(4) },
  { id: generateId(), type: 'hygiene', name: 'Hygiene Kits', quantity: 150, capacity: 300, unit: 'kits', lastUpdated: hoursAgo(6) },
  { id: generateId(), type: 'tools', name: 'Tool Kits', quantity: 25, capacity: 50, unit: 'sets', lastUpdated: hoursAgo(8) },
];

// Chart data for dashboard analytics
export const MOCK_DAILY_REQUESTS = [
  { day: 'Mon', requests: 12, resolved: 8 },
  { day: 'Tue', requests: 19, resolved: 14 },
  { day: 'Wed', requests: 28, resolved: 20 },
  { day: 'Thu', requests: 35, resolved: 25 },
  { day: 'Fri', requests: 24, resolved: 22 },
  { day: 'Sat', requests: 18, resolved: 15 },
  { day: 'Sun', requests: 10, resolved: 9 },
];

export const MOCK_CATEGORY_DISTRIBUTION = [
  { name: 'Rescue', value: 15, fill: '#ff4757' },
  { name: 'Medical', value: 22, fill: '#ff6b35' },
  { name: 'Food & Water', value: 35, fill: '#ffc542' },
  { name: 'Shelter', value: 18, fill: '#45aaf2' },
  { name: 'Transport', value: 8, fill: '#a55eea' },
  { name: 'Other', value: 12, fill: '#26de81' },
];

export const MOCK_RESPONSE_TIMES = [
  { hour: '6AM', avgMinutes: 45 },
  { hour: '8AM', avgMinutes: 32 },
  { hour: '10AM', avgMinutes: 28 },
  { hour: '12PM', avgMinutes: 38 },
  { hour: '2PM', avgMinutes: 25 },
  { hour: '4PM', avgMinutes: 30 },
  { hour: '6PM', avgMinutes: 42 },
  { hour: '8PM', avgMinutes: 50 },
];
